version: '3'

services:

  registry:
    image: sixeyed/registry:2.6.0-nanoserver
    restart: unless-stopped
    ports:
      - 5000
    volumes:
      - c:\registry:c:\data
    networks:
      home:
        ipv4_address: 172.19.1.200

  bonobo:
    image: sixeyed/bonobo:6.1.0-windowsservercore
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - c:\bonobo:c:\data
    networks:
      home:
        ipv4_address: 172.19.1.201

  jenkins:
    image: ${dockerId}/jenkins:configured
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - c:\jenkins:c:\data
    networks:
      home:
        ipv4_address: 172.19.1.202

networks:
  home:
    external:
      name: nat