version: "3.1"

services:
  db:
    image: mongo:4.0.1-xenial
    command: mongod --smallfiles
    networks:
      - chat-net

  rocketchat:
    image: rocketchat/rocket.chat:0.65.2
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=http://chat.dwwx.space
    networks:
      - chat-net
    deploy:
      labels:
        com.docker.lb.hosts: chat.dwwx.space
        com.docker.lb.port: 3000

networks:
  chat-net:
