version: '3.1'

services:
  
  signup-db:
    image: ${dockerId}/signup-db
    volumes:
      - C:\mssql:C:\data
    env_file:
      - db-credentials.env
    restart: always
    networks:
      - app-net

  signup-web:
    image: ${dockerId}/signup-web:1.4
    ports:
      - "80:80"
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    restart: always
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    restart: always
    networks:
      - app-net

  signup-save-handler:
    image: ${dockerId}/signup-save-handler:2
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    restart: always
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    restart: always
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601"
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - app-net

  signup-index-handler:
    image: ${dockerid}/signup-index-handler:2
    depends_on:
      - elasticsearch
      - message-queue
    restart: always
    networks:
      - app-net

  prometheus:
    image: ${dockerid}/signup-prometheus
    networks:
      - app-net

  grafana:
    image: ${dockerid}/signup-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat