# v1 is the original monolith with SQL Server
version: '3.1'

services:
  
  signup-db:
    image: microsoft/mssql-server-windows-express:2016-sp1
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dwwx/signup-web:nsb
    ports:
      - "8020:80"
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    volumes:      
      - C:\web-logs:C:\web-app\App_Data
    depends_on:
      - signup-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat