# v4 uses asynchronous messaging with NATS
version: '3.1'

services:
  
  signup-db:
    image: microsoft/mssql-server-windows-express:2016-sp1
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dwwx/signup-web:v2
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  homepage:
    image: dwwx/homepage
    networks:
      - app-net

  proxy:
    image: dwwx/reverse-proxy
    ports:
      - "8020:80"
    depends_on:
      - signup-web
      - homepage
    networks:
      - app-net

  message-queue:
    image: nats:1.3.0-nanoserver
    networks:
      - app-net

  signup-save-handler:
    image: dwwx/save-handler
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat