# v8 adds restart policies
version: '3.1'

services:
  
  signup-db:
    image: dwwx/signup-db
    volumes:
      - C:\mssql:C:\data
    restart: always
    networks:
      - app-net

  signup-web:
    image: dwwx/signup-web:v3
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.ApiReferenceDataLoader
      - ReferenceDataApi:Url=http://reference-data-api/api
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
    depends_on:
      - signup-db
      - reference-data-api
      - message-queue
    restart: always
    networks:
      - app-net

  homepage:
    image: dwwx/homepage
    restart: always
    networks:
      - app-net

  proxy:
    image: dwwx/reverse-proxy
    ports:
      - "8020:80"
    depends_on:
      - signup-web
      - homepage
    restart: always
    networks:
      - app-net

  reference-data-api:
    image: dwwx/reference-data-api
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    depends_on:
      - signup-db
    restart: always
    networks:
      - app-net

  message-queue:
    image: nats:1.3.0-nanoserver
    restart: always
    networks:
      - app-net

  signup-save-handler:
    image: dwwx/save-handler:v2
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!      
    depends_on:
      - signup-db
      - message-queue
    restart: always
    networks:
      - app-net

  signup-index-handler:
    image: dwwx/index-handler:v2
    depends_on:
      - elasticsearch
      - message-queue
    restart: always
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:5.6.11-nanoserver-sac2016
    volumes:
      - C:\es:C:\data
    restart: always
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:5.6.11-windowsservercore-ltsc2016
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - app-net

  prometheus:
    image: dwwx/prometheus
    volumes:
      - C:\prom:C:\prometheus
    restart: unless-stopped
    networks:
      - app-net

  grafana:
    image: dwwx/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat