version: '3.1'

services:
  
  signup-db:
    image: ${dockerId}/signup-db
    env_file:
      - db-credentials.env
    networks:
      - app-net

  signup-web:
    image: ${dockerId}/signup-web:1.4
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-save-handler:
    image: ${dockerId}/signup-save-handler:2
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    depends_on:
      - elasticsearch
    networks:
      - app-net

  signup-index-handler:
    image: ${dockerid}/signup-index-handler:2
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  prometheus:
    image: ${dockerid}/signup-prometheus
    networks:
      - app-net

  grafana:
    image: ${dockerid}/signup-grafana
    depends_on:
      - prometheus
    networks:
      - app-net