version: '3.3'

services:
  
  signup-db:
    image: sixeyed/signup-db:rtm
    env_file:
      - db-credentials.env
    networks:
      - app-net

  signup-web:
    image: sixeyed/signup-web:rtm
    env_file:
      - db-credentials.env
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-save-handler:
    image: sixeyed/signup-save-handler:rtm
    env_file:
      - db-credentials.env
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    networks:
      - app-net

  signup-index-handler:
    image: sixeyed/signup-index-handler:rtm
    networks:
      - app-net

  prometheus:
    image: sixeyed/signup-prometheus:rtm
    networks:
      - app-net

  grafana:
    image: sixeyed/signup-grafana:rtm
    networks:
      - app-net