version: '3.1'

services:
  
  signup-db:
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!

  signup-web:
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
      - Dependencies:IProspectSave=SignUp.Web.ProspectSave.NServiceBusProspectSave
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.NServiceBusReferenceDataLoader
      - NServiceBus:Transport=LearningTransport
    volumes:      
      - ${TEST_STATE}:C:\web-app\App_Data
      - ${TEST_STATE}:C:\nsb
    depends_on:
      - signup-db
      
  signup-save-handler:
    environment:
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
      - NServiceBus:Transport=LearningTransport
    volumes:
      - ${TEST_STATE}:C:\nsb
    depends_on:
      - signup-db

  signup-index-handler:
    environment:       
      - NServiceBus:Transport=LearningTransport
    volumes:
      - ${TEST_STATE}:C:\nsb
    depends_on:
      - elasticsearch

  kibana:
    depends_on:
      - elasticsearch

  signup-reference-data-handler:
    environment:
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!       
      - NServiceBus:Transport=LearningTransport
    volumes:
      - ${TEST_STATE}:C:\nsb
    depends_on:
      - signup-db

networks:
  app-net:
    external:
      name: nat