version: '3.1'

services:

  signup-web:
    image: dwwx/signup-web:v2
    build:
      context: ..
      dockerfile: ./docker/frontend-web/v2/Dockerfile

  signup-save-handler:
    image: dwwx/save-handler:v2
    build:
      context: ..
      dockerfile: ./docker/metrics-application/save-handler/Dockerfile

  signup-index-handler:
    image: dwwx/index-handler:v2
    build:
      context: ..
      dockerfile: ./docker/metrics-application/index-handler/Dockerfile