version: '3.1'

services:

  signup-web:
    build:
      context: ..
      dockerfile: ./docker/frontend-web/v2/Dockerfile

  signup-save-handler:
    build:
      context: ..
      dockerfile: ./docker/backend-async-messaging/save-handler/Dockerfile

  signup-index-handler:
    build:
      context: ..
      dockerfile: ./docker/backend-analytics/index-handler/Dockerfile

  signup-reference-data-handler:
    build:
      context: ..
      dockerfile: ./docker/backend-rest-api/reference-data-handler/Dockerfile

  e2e-tests:
    image: dwwx/e2e-tests:nsb
    build:
      context: ..
      dockerfile: ./docker/e2e-tests/Dockerfile